// Code generated by go generate; DO NOT EDIT.
package version

const (
    BuildBranch = "regenerate-2020-03-25.10.25.12"
    BuildTime int64 = 1585245373
    Version = ScloudVersion
    Commit = "bc63b7b-dirty"
)
