// Code generated by go generate; DO NOT EDIT.
package version

const (
    BuildBranch = "regenerate-2020-04-15.11.04.57"
    BuildTime int64 = 1586973958
    Version = ScloudVersion
    Commit = "ad19e50-dirty"
)
