// Code generated by go generate; DO NOT EDIT.
package version

const (
    BuildBranch = "streams-manual-compile"
    BuildTime int64 = 1590089759
    Version = ScloudVersion
    Commit = "f301f54-dirty"
)
