/*
 * Copyright © 2019 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Metadata Catalog
 *
 * With the Metadata Catalog you can create and manage knowledge objects such as datasets, fields, rules, actions, dashboards, and workflows.
 *
 * API version: v2beta1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
 */

package catalog

// ListActionsForRuleQueryParams represents valid query parameters for the ListActionsForRule operation
// For convenience ListActionsForRuleQueryParams can be formed in a single statement, for example:
//     `v := ListActionsForRuleQueryParams{}.SetFilter(...)`
type ListActionsForRuleQueryParams struct {
	// Filter : A filter query to apply to the rule.
	Filter string `key:"filter"`
}

func (q ListActionsForRuleQueryParams) SetFilter(v string) ListActionsForRuleQueryParams {
	q.Filter = v
	return q
}

// ListActionsForRuleByIdQueryParams represents valid query parameters for the ListActionsForRuleById operation
// For convenience ListActionsForRuleByIdQueryParams can be formed in a single statement, for example:
//     `v := ListActionsForRuleByIdQueryParams{}.SetFilter(...)`
type ListActionsForRuleByIdQueryParams struct {
	// Filter : A filter query to apply to the actions.
	Filter string `key:"filter"`
}

func (q ListActionsForRuleByIdQueryParams) SetFilter(v string) ListActionsForRuleByIdQueryParams {
	q.Filter = v
	return q
}

// ListAnnotationsForDatasetByIdQueryParams represents valid query parameters for the ListAnnotationsForDatasetById operation
// For convenience ListAnnotationsForDatasetByIdQueryParams can be formed in a single statement, for example:
//     `v := ListAnnotationsForDatasetByIdQueryParams{}.SetFilter(...)`
type ListAnnotationsForDatasetByIdQueryParams struct {
	// Filter : A filter query to apply to the annotations.
	Filter string `key:"filter"`
}

func (q ListAnnotationsForDatasetByIdQueryParams) SetFilter(v string) ListAnnotationsForDatasetByIdQueryParams {
	q.Filter = v
	return q
}

// ListAnnotationsForDatasetByResourceNameQueryParams represents valid query parameters for the ListAnnotationsForDatasetByResourceName operation
// For convenience ListAnnotationsForDatasetByResourceNameQueryParams can be formed in a single statement, for example:
//     `v := ListAnnotationsForDatasetByResourceNameQueryParams{}.SetFilter(...)`
type ListAnnotationsForDatasetByResourceNameQueryParams struct {
	// Filter : A filter query to apply to the annotations.
	Filter string `key:"filter"`
}

func (q ListAnnotationsForDatasetByResourceNameQueryParams) SetFilter(v string) ListAnnotationsForDatasetByResourceNameQueryParams {
	q.Filter = v
	return q
}

// ListDatasetsQueryParams represents valid query parameters for the ListDatasets operation
// For convenience ListDatasetsQueryParams can be formed in a single statement, for example:
//     `v := ListDatasetsQueryParams{}.SetCount(...).SetFilter(...).SetOrderby(...)`
type ListDatasetsQueryParams struct {
	// Count : The maximum number of results to return.
	Count *int32 `key:"count"`
	// Filter : A filter to apply to the dataset list. The filter must be a SPL predicate expression.
	Filter string `key:"filter"`
	// Orderby : A list of fields to order the results by.  You can specify either ascending or descending order using \&quot;&lt;field&gt; asc\&quot; or \&quot;&lt;field&gt; desc.  Ascending order is the default.
	Orderby []string `key:"orderby"`
}

func (q ListDatasetsQueryParams) SetCount(v int32) ListDatasetsQueryParams {
	q.Count = &v
	return q
}

func (q ListDatasetsQueryParams) SetFilter(v string) ListDatasetsQueryParams {
	q.Filter = v
	return q
}

func (q ListDatasetsQueryParams) SetOrderby(v []string) ListDatasetsQueryParams {
	q.Orderby = v
	return q
}

// ListFieldsQueryParams represents valid query parameters for the ListFields operation
// For convenience ListFieldsQueryParams can be formed in a single statement, for example:
//     `v := ListFieldsQueryParams{}.SetFilter(...)`
type ListFieldsQueryParams struct {
	// Filter : A filter query to apply to the the field list.
	Filter string `key:"filter"`
}

func (q ListFieldsQueryParams) SetFilter(v string) ListFieldsQueryParams {
	q.Filter = v
	return q
}

// ListFieldsForDatasetQueryParams represents valid query parameters for the ListFieldsForDataset operation
// For convenience ListFieldsForDatasetQueryParams can be formed in a single statement, for example:
//     `v := ListFieldsForDatasetQueryParams{}.SetFilter(...)`
type ListFieldsForDatasetQueryParams struct {
	// Filter : A filter to apply to the dataset.
	Filter string `key:"filter"`
}

func (q ListFieldsForDatasetQueryParams) SetFilter(v string) ListFieldsForDatasetQueryParams {
	q.Filter = v
	return q
}

// ListFieldsForDatasetByIdQueryParams represents valid query parameters for the ListFieldsForDatasetById operation
// For convenience ListFieldsForDatasetByIdQueryParams can be formed in a single statement, for example:
//     `v := ListFieldsForDatasetByIdQueryParams{}.SetFilter(...)`
type ListFieldsForDatasetByIdQueryParams struct {
	// Filter : A filter to apply to a specified dataset. The filter must be a SPL predicate expression.
	Filter string `key:"filter"`
}

func (q ListFieldsForDatasetByIdQueryParams) SetFilter(v string) ListFieldsForDatasetByIdQueryParams {
	q.Filter = v
	return q
}

// ListModulesQueryParams represents valid query parameters for the ListModules operation
// For convenience ListModulesQueryParams can be formed in a single statement, for example:
//     `v := ListModulesQueryParams{}.SetFilter(...)`
type ListModulesQueryParams struct {
	// Filter : A filter to apply to the modules.
	Filter string `key:"filter"`
}

func (q ListModulesQueryParams) SetFilter(v string) ListModulesQueryParams {
	q.Filter = v
	return q
}

// ListRelationshipsQueryParams represents valid query parameters for the ListRelationships operation
// For convenience ListRelationshipsQueryParams can be formed in a single statement, for example:
//     `v := ListRelationshipsQueryParams{}.SetFilter(...)`
type ListRelationshipsQueryParams struct {
	// Filter : A filter to apply to the complete set of relationships.
	Filter string `key:"filter"`
}

func (q ListRelationshipsQueryParams) SetFilter(v string) ListRelationshipsQueryParams {
	q.Filter = v
	return q
}

// ListRulesQueryParams represents valid query parameters for the ListRules operation
// For convenience ListRulesQueryParams can be formed in a single statement, for example:
//     `v := ListRulesQueryParams{}.SetFilter(...)`
type ListRulesQueryParams struct {
	// Filter : A query filter to apply to the complete set of rules.
	Filter string `key:"filter"`
}

func (q ListRulesQueryParams) SetFilter(v string) ListRulesQueryParams {
	q.Filter = v
	return q
}

// ListWorkflowBuildsQueryParams represents valid query parameters for the ListWorkflowBuilds operation
// For convenience ListWorkflowBuildsQueryParams can be formed in a single statement, for example:
//     `v := ListWorkflowBuildsQueryParams{}.SetFilter(...)`
type ListWorkflowBuildsQueryParams struct {
	// Filter : A filter to apply to the workflow builds. Must be a SPL predicate expression.
	Filter string `key:"filter"`
}

func (q ListWorkflowBuildsQueryParams) SetFilter(v string) ListWorkflowBuildsQueryParams {
	q.Filter = v
	return q
}

// ListWorkflowRunsQueryParams represents valid query parameters for the ListWorkflowRuns operation
// For convenience ListWorkflowRunsQueryParams can be formed in a single statement, for example:
//     `v := ListWorkflowRunsQueryParams{}.SetFilter(...)`
type ListWorkflowRunsQueryParams struct {
	// Filter : A filter to apply to the workflow runs for specified workflow build ID. Must be an SPL predicate expression.
	Filter string `key:"filter"`
}

func (q ListWorkflowRunsQueryParams) SetFilter(v string) ListWorkflowRunsQueryParams {
	q.Filter = v
	return q
}

// ListWorkflowsQueryParams represents valid query parameters for the ListWorkflows operation
// For convenience ListWorkflowsQueryParams can be formed in a single statement, for example:
//     `v := ListWorkflowsQueryParams{}.SetFilter(...)`
type ListWorkflowsQueryParams struct {
	// Filter : A filter to apply to the workflows. Must be a SPL predicate expression.
	Filter string `key:"filter"`
}

func (q ListWorkflowsQueryParams) SetFilter(v string) ListWorkflowsQueryParams {
	q.Filter = v
	return q
}
