// Package forwarders -- generated by scloudgen
// !! DO NOT EDIT !!
//
package forwarders

import (
	"fmt"

	"github.com/spf13/cobra"
)

// AddCertificate -- impl
func AddCertificate(cmd *cobra.Command, args []string) error {
	fmt.Printf("called AddCertificate\n")
	return nil
}

// DeleteCertificate -- impl
func DeleteCertificate(cmd *cobra.Command, args []string) error {
	fmt.Printf("called DeleteCertificate\n")
	return nil
}

// DeleteCertificates -- impl
func DeleteCertificates(cmd *cobra.Command, args []string) error {
	fmt.Printf("called DeleteCertificates\n")
	return nil
}

// ListCertificates -- impl
func ListCertificates(cmd *cobra.Command, args []string) error {
	fmt.Printf("called ListCertificates\n")
	return nil
}
