// Package kvstore -- generated by scloudgen
// !! DO NOT EDIT !!
//
package kvstore

import (
	"github.com/spf13/cobra"
	impl "github.com/splunk/splunk-cloud-sdk-go/scloud_generated/pkg/kvstore"
)

// createIndex -- Creates an index on a collection.
var createIndexCmd = &cobra.Command{
	Use:   "create-index",
	Short: "Creates an index on a collection.",
	RunE:  impl.CreateIndex,
}

// deleteIndex -- Removes an index from a collection.
var deleteIndexCmd = &cobra.Command{
	Use:   "delete-index",
	Short: "Removes an index from a collection.",
	RunE:  impl.DeleteIndex,
}

// deleteRecordByKey -- Deletes a record with a given key.
var deleteRecordByKeyCmd = &cobra.Command{
	Use:   "delete-record-by-key",
	Short: "Deletes a record with a given key.",
	RunE:  impl.DeleteRecordByKey,
}

// deleteRecords -- Removes records in a collection that match the query.
var deleteRecordsCmd = &cobra.Command{
	Use:   "delete-records",
	Short: "Removes records in a collection that match the query.",
	RunE:  impl.DeleteRecords,
}

// getRecordByKey -- Returns a record with a given key.
var getRecordByKeyCmd = &cobra.Command{
	Use:   "get-record-by-key",
	Short: "Returns a record with a given key.",
	RunE:  impl.GetRecordByKey,
}

// insertRecord -- Inserts a record into a collection.
var insertRecordCmd = &cobra.Command{
	Use:   "insert-record",
	Short: "Inserts a record into a collection.",
	RunE:  impl.InsertRecord,
}

// insertRecords -- Inserts multiple records in a single request.
var insertRecordsCmd = &cobra.Command{
	Use:   "insert-records",
	Short: "Inserts multiple records in a single request.",
	RunE:  impl.InsertRecords,
}

// listIndexes -- Returns a list of all indexes on a collection.
var listIndexesCmd = &cobra.Command{
	Use:   "list-indexes",
	Short: "Returns a list of all indexes on a collection.",
	RunE:  impl.ListIndexes,
}

// listRecords -- Use key-value query parameters to filter fields. Fields are implicitly ANDed and values for the same field are implicitly ORed.
var listRecordsCmd = &cobra.Command{
	Use:   "list-records",
	Short: "Use key-value query parameters to filter fields. Fields are implicitly ANDed and values for the same field are implicitly ORed.",
	RunE:  impl.ListRecords,
}

// ping -- Returns the health status from the database.
var pingCmd = &cobra.Command{
	Use:   "ping",
	Short: "Returns the health status from the database.",
	RunE:  impl.Ping,
}

// putRecord -- Updates the record with a given key, either by inserting or replacing the record.
var putRecordCmd = &cobra.Command{
	Use:   "put-record",
	Short: "Updates the record with a given key, either by inserting or replacing the record.",
	RunE:  impl.PutRecord,
}

// queryRecords -- Returns a list of query records in a collection.
var queryRecordsCmd = &cobra.Command{
	Use:   "query-records",
	Short: "Returns a list of query records in a collection.",
	RunE:  impl.QueryRecords,
}

func init() {
	kvstoreCmd.AddCommand(createIndexCmd)
	var createIndexCollection string
	createIndexCmd.Flags().StringVar(&createIndexCollection, "collection", "", "The name of the collection.")
	createIndexCmd.MarkFlagRequired("collection")
	var createIndexFields string
	createIndexCmd.Flags().StringVar(&createIndexFields, "fields", "", "")
	createIndexCmd.MarkFlagRequired("fields")
	var createIndexName string
	createIndexCmd.Flags().StringVar(&createIndexName, "name", "", "The name of the index.")
	createIndexCmd.MarkFlagRequired("name")

	kvstoreCmd.AddCommand(deleteIndexCmd)
	var deleteIndexCollection string
	deleteIndexCmd.Flags().StringVar(&deleteIndexCollection, "collection", "", "The name of the collection.")
	deleteIndexCmd.MarkFlagRequired("collection")
	var deleteIndexIndex string
	deleteIndexCmd.Flags().StringVar(&deleteIndexIndex, "index", "", "The name of the index.")
	deleteIndexCmd.MarkFlagRequired("index")

	kvstoreCmd.AddCommand(deleteRecordByKeyCmd)
	var deleteRecordByKeyCollection string
	deleteRecordByKeyCmd.Flags().StringVar(&deleteRecordByKeyCollection, "collection", "", "The name of the collection.")
	deleteRecordByKeyCmd.MarkFlagRequired("collection")
	var deleteRecordByKeyKey string
	deleteRecordByKeyCmd.Flags().StringVar(&deleteRecordByKeyKey, "key", "", "The key of the record.")
	deleteRecordByKeyCmd.MarkFlagRequired("key")

	kvstoreCmd.AddCommand(deleteRecordsCmd)
	var deleteRecordsCollection string
	deleteRecordsCmd.Flags().StringVar(&deleteRecordsCollection, "collection", "", "The name of the collection.")
	deleteRecordsCmd.MarkFlagRequired("collection")

	var deleteRecordsQuery string
	deleteRecordsCmd.Flags().StringVar(&deleteRecordsQuery, "query", "", "Query JSON expression.")

	kvstoreCmd.AddCommand(getRecordByKeyCmd)
	var getRecordByKeyCollection string
	getRecordByKeyCmd.Flags().StringVar(&getRecordByKeyCollection, "collection", "", "The name of the collection.")
	getRecordByKeyCmd.MarkFlagRequired("collection")
	var getRecordByKeyKey string
	getRecordByKeyCmd.Flags().StringVar(&getRecordByKeyKey, "key", "", "The key of the record.")
	getRecordByKeyCmd.MarkFlagRequired("key")

	kvstoreCmd.AddCommand(insertRecordCmd)
	var insertRecordCollection string
	insertRecordCmd.Flags().StringVar(&insertRecordCollection, "collection", "", "The name of the collection.")
	insertRecordCmd.MarkFlagRequired("collection")

	kvstoreCmd.AddCommand(insertRecordsCmd)
	var insertRecordsCollection string
	insertRecordsCmd.Flags().StringVar(&insertRecordsCollection, "collection", "", "The name of the collection.")
	insertRecordsCmd.MarkFlagRequired("collection")

	kvstoreCmd.AddCommand(listIndexesCmd)
	var listIndexesCollection string
	listIndexesCmd.Flags().StringVar(&listIndexesCollection, "collection", "", "The name of the collection.")
	listIndexesCmd.MarkFlagRequired("collection")

	kvstoreCmd.AddCommand(listRecordsCmd)
	var listRecordsCollection string
	listRecordsCmd.Flags().StringVar(&listRecordsCollection, "collection", "", "The name of the collection.")
	listRecordsCmd.MarkFlagRequired("collection")

	var listRecordsCount string
	listRecordsCmd.Flags().StringVar(&listRecordsCount, "count", "", "Maximum number of records to return.")
	var listRecordsFields string
	listRecordsCmd.Flags().StringVar(&listRecordsFields, "fields", "", "Comma-separated list of fields to include or exclude.")
	var listRecordsFilters string
	listRecordsCmd.Flags().StringVar(&listRecordsFilters, "filters", "", "")
	var listRecordsOffset string
	listRecordsCmd.Flags().StringVar(&listRecordsOffset, "offset", "", "Number of records to skip from the start.")
	var listRecordsOrderby string
	listRecordsCmd.Flags().StringVar(&listRecordsOrderby, "orderby", "", "Sort order. Format is `<field>:<sort order>`. Valid sort orders are 1 for ascending, -1 for descending.")

	kvstoreCmd.AddCommand(pingCmd)

	kvstoreCmd.AddCommand(putRecordCmd)
	var putRecordCollection string
	putRecordCmd.Flags().StringVar(&putRecordCollection, "collection", "", "The name of the collection.")
	putRecordCmd.MarkFlagRequired("collection")
	var putRecordKey string
	putRecordCmd.Flags().StringVar(&putRecordKey, "key", "", "The key of the record.")
	putRecordCmd.MarkFlagRequired("key")

	var putRecordIfMatch string
	putRecordCmd.Flags().StringVar(&putRecordIfMatch, "if-match", "", "Record version identifier.")

	kvstoreCmd.AddCommand(queryRecordsCmd)
	var queryRecordsCollection string
	queryRecordsCmd.Flags().StringVar(&queryRecordsCollection, "collection", "", "The name of the collection.")
	queryRecordsCmd.MarkFlagRequired("collection")

	var queryRecordsCount string
	queryRecordsCmd.Flags().StringVar(&queryRecordsCount, "count", "", "Maximum number of records to return.")
	var queryRecordsFields string
	queryRecordsCmd.Flags().StringVar(&queryRecordsFields, "fields", "", "Comma-separated list of fields to include or exclude.")
	var queryRecordsOffset string
	queryRecordsCmd.Flags().StringVar(&queryRecordsOffset, "offset", "", "Number of records to skip from the start.")
	var queryRecordsOrderby string
	queryRecordsCmd.Flags().StringVar(&queryRecordsOrderby, "orderby", "", "Sort order. Format is `<field>:<sort order>`. Valid sort orders are 1 for ascending, -1 for descending.")
	var queryRecordsQuery string
	queryRecordsCmd.Flags().StringVar(&queryRecordsQuery, "query", "", "Query JSON expression.")

}
