// Package streams -- generated by scloudgen
// !! DO NOT EDIT !!
//
package streams

import (
	"encoding/json"
	"io/ioutil"

	"github.com/splunk/splunk-cloud-sdk-go/cmd/scloud_generated/auth"
	model "github.com/splunk/splunk-cloud-sdk-go/services/streams"
)

// CreatePipeline Creates a pipeline.
func CreatePipelineOverride(filename string) (*model.PipelineResponse, error) {
	client, err := auth.GetClient()
	if err != nil {
		return nil, err
	}

	byets, err := ioutil.ReadFile(filename)
	if err != nil {
		return nil, err
	}

	var data model.PipelineRequest
	err = json.Unmarshal(byets, &data)
	if err != nil {
		return nil, err
	}

	resp, err := client.StreamsService.CreatePipeline(data)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
