components:
  responses:
    badRequestError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request isn't valid.
    errorResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Error response.
    forbiddenError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The operation isn't authorized.
    internalError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: An internal service error occurred.
    noContentResponse:
      description: The certificate was removed successfully.
    notFoundError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The resource wasn't found.
    successCertUploadResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CertificateInfo'
      description: The certificate on the tenant slot was added successfully.
    successListCertificateResponse:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/CertificateInfo'
            type: array
      description: The list of certificates was returned successfully.
    tooManyRequestsError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Too many requests were sent.
    unauthorizedError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The user isn't authenticated.
  schemas:
    Certificate:
      properties:
        pem:
          type: string
      required:
      - pem
      type: object
    CertificateInfo:
      properties:
        content:
          type: string
        hash:
          type: string
        issuer:
          type: string
        lastUpdate:
          format: date-time
          type: string
        notAfter:
          format: date-time
          type: string
        notBefore:
          format: date-time
          type: string
        slot:
          format: int64
          type: integer
        subject:
          type: string
      type: object
    Error:
      properties:
        code:
          type: string
        details:
          type: object
        message:
          type: string
      type: object
info:
  description: Send data from a Splunk forwarder to the Splunk Forwarder service in Splunk Cloud Services.
  title: Splunk Forwarder Service
  version: v2beta1.4
openapi: 3.0.0
paths:
  /{tenant}/forwarders/v2beta1/certificates:
    delete:
      operationId: deleteCertificates
      parameters:
      - in: path
        name: tenant
        required: true
        schema:
          type: string
      responses:
        "204":
          $ref: '#/components/responses/noContentResponse'
        "400":
          $ref: '#/components/responses/badRequestError'
        "401":
          $ref: '#/components/responses/unauthorizedError'
        "403":
          $ref: '#/components/responses/forbiddenError'
        "404":
          $ref: '#/components/responses/notFoundError'
        "429":
          $ref: '#/components/responses/tooManyRequestsError'
        "500":
          $ref: '#/components/responses/internalError'
      summary: Removes all certificates on a tenant.
      tags:
      - Certificates
      x-auth-required: true
      x-authz-scope: forwarders.certificates.delete
    get:
      operationId: listCertificates
      parameters:
      - in: path
        name: tenant
        required: true
        schema:
          type: string
      responses:
        "200":
          $ref: '#/components/responses/successListCertificateResponse'
        "400":
          $ref: '#/components/responses/badRequestError'
        "401":
          $ref: '#/components/responses/unauthorizedError'
        "403":
          $ref: '#/components/responses/forbiddenError'
        "404":
          $ref: '#/components/responses/notFoundError'
        "429":
          $ref: '#/components/responses/tooManyRequestsError'
        "500":
          $ref: '#/components/responses/internalError'
      summary: Returns a list of all certificates for a tenant.
      tags:
      - Certificates
      x-auth-required: true
      x-authz-scope: forwarders.certificates.read
    post:
      operationId: addCertificate
      parameters:
      - in: path
        name: tenant
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Certificate'
      responses:
        "200":
          $ref: '#/components/responses/successCertUploadResponse'
        "400":
          $ref: '#/components/responses/badRequestError'
        "401":
          $ref: '#/components/responses/unauthorizedError'
        "403":
          $ref: '#/components/responses/forbiddenError'
        "404":
          $ref: '#/components/responses/notFoundError'
        "409":
          $ref: '#/components/responses/badRequestError'
        "429":
          $ref: '#/components/responses/tooManyRequestsError'
        "500":
          $ref: '#/components/responses/internalError'
      summary: Adds a certificate to a vacant slot on a tenant.
      tags:
      - Certificates
      x-auth-required: true
      x-authz-scope: forwarders.certificates.write
  /{tenant}/forwarders/v2beta1/certificates/{slot}:
    delete:
      operationId: deleteCertificate
      parameters:
      - in: path
        name: tenant
        required: true
        schema:
          type: string
      - in: path
        name: slot
        required: true
        schema:
          type: string
      responses:
        "204":
          $ref: '#/components/responses/noContentResponse'
        "400":
          $ref: '#/components/responses/badRequestError'
        "401":
          $ref: '#/components/responses/unauthorizedError'
        "403":
          $ref: '#/components/responses/forbiddenError'
        "404":
          $ref: '#/components/responses/notFoundError'
        "429":
          $ref: '#/components/responses/tooManyRequestsError'
        "500":
          $ref: '#/components/responses/internalError'
      summary: Removes a certificate on a particular slot on a tenant.
      tags:
      - Certificates
      x-auth-required: true
      x-authz-scope: forwarders.certificates.delete
servers:
- url: /

# Retrieved from scp-openapi commit 75824d71791e0b0bdf66dbcce7dd9dc1e7061407 path: forwarders/v2beta1/openapi.yaml